apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-app
  labels:
    app: my-first-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-first-app
  template:
    metadata:
      labels:
        app: my-first-app
    spec:
      containers:
        - name: my-first-app
          image: my-first-app:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: my-first-app-config
                  key: GREETING
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5 
